GET  https://api.daoyitong.com/api/v1/account/freeLoginAes?aesPhone=cUGeDTkvwMJvmaxGPP3YX%2BM0yQctTKQbf91ouVw5y7k%3D

# GET  http://static-imgdaoyitong.health.ikang.com/users/1585808269544416.jpg?t=1610681848318
